### ISSUE TITLE
ConfigurationException on startup

### ISSUE THREAD

**Issue by darrenhaken** [HubSpot/dropwizard-guicier#9]
When I start the application I receive the following error:
```
WARN  [2016-07-12 19:54:42,640] org.glassfish.jersey.server.internal.JerseyResourceContext: Lookup and initialization failed for a resource class: class org.glassfish.jersey.server.validation.internal.InjectingConstraintValidatorFactory.
! com.google.inject.ConfigurationException: Guice configuration errors:
!
! 1) Explicit bindings are required and org.glassfish.jersey.server.validation.internal.InjectingConstraintValidatorFactory is not explicitly bound.
!   while locating org.glassfish.jersey.server.validation.internal.InjectingConstraintValidatorFactory
!
! 1 error
! at com.google.inject.internal.InjectorImpl.getBinding(InjectorImpl.java:159) ~[guice-4.0.jar:na]
! at com.google.inject.internal.InjectorImpl.getBinding(InjectorImpl.java:67) ~[guice-4.0.jar:na]
! at com.squarespace.jersey2.guice.GuiceJustInTimeResolver.findBinding(GuiceJustInTimeResolver.java:95) ~[jersey2-guice-impl-1.0.6.jar:na]
! at com.squarespace.jersey2.guice.GuiceJustInTimeResolver.justInTimeResolution(GuiceJustInTimeResolver.java:54) ~[jersey2-guice-impl-1.0.6.jar:na]
! at org.jvnet.hk2.internal.ServiceLocatorImpl.secondChanceResolve(ServiceLocatorImpl.java:506) [hk2-locator-2.4.0-b34.jar:na]
! ... 71 common frames omitted
! Causing: org.glassfish.hk2.api.MultiException: A MultiException has 1 exceptions.  They are:
! 1. com.google.inject.ConfigurationException: Guice configuration errors:
!
! 1) Explicit bindings are required and org.glassfish.jersey.server.validation.internal.InjectingConstraintValidatorFactory is not explicitly bound.
!   while locating org.glassfish.jersey.server.validation.internal.InjectingConstraintValidatorFactory
!
! 1 error
```

**Comment by darrenhaken** [comment]
Here is the initialize method in Application startup

```Java
 @Override
    public void initialize(Bootstrap<AppConfiguration> bootstrap) {
        bootstrap.addBundle(GuiceBundle.defaultBuilder(AppConfiguration.class)
            .modules(new ContainerModule())
            .build());
    }
```

**Comment by darrenhaken** [comment]
Here is the Module:

```Java
public class ContainerModule extends DropwizardAwareModule<AppConfiguration>{

    @Override
    public void configure(Binder binder) {
        binder.bind(HealthResource.class);
    }
}
```

**Comment by darrenhaken** [comment]
Here is the resource:
```Java
@Path("/health/status")
@Produces(MediaType.APPLICATION_JSON)
public class HealthResource {

    private class HealthResponse {
        @JsonProperty
        private String status;

        public HealthResponse() {
        }

        public HealthResponse(String status) {
            this.status = status;
        }

        public String getStatus() {
            return status;
        }

        public void setStatus(String status) {
            this.status = status;
        }
    }

    @Inject
    public HealthResource() {

    }

    @GET
    @Timed
    public HealthResponse processImage() {
        return new HealthResponse("OK");
    }
}
```

**Comment by jhaber** [comment]
Hmm, I'm not able to reproduce this issue with the code snippets you supplied. I tried to fill in the missing pieces to turn it into a runnable application, available [here](https://github.com/jhaber/dropwizard-guicier-issue9/blob/master/README.md) and it starts up fine and hitting `localhost:8080/app/health/status` returns:

```bash
➜  ~ http localhost:8080/app/health/status     
HTTP/1.1 200 OK
Content-Length: 15
Content-Type: application/json
Date: Wed, 13 Jul 2016 15:21:32 GMT
Vary: Accept-Encoding

{
    "status": "OK"
}
```

**Comment by darrenhaken** [comment]
I'm trying to shrink down my project now and push a sample project on Github for you to look at. Watch this space

**Comment by darrenhaken** [comment]
I was able to reproduce it with this: https://github.com/darrenhaken/dropwizard-guicier-issue9

**Comment by darrenhaken** [comment]
To launch the app run:
```Bash
./gradlew run
```

**Comment by jhaber** [comment]
I was getting an exception on build about a wrapper properties file not existing so I did
```
echo 'distributionUrl=http\://services.gradle.org/distributions/gradle-2.14-bin.zip' > gradle/wrapper/gradle-wrapper.properties
```
After that I saw the exception you were talking about, but the app did actually start up and was serving requests successfully. I believe the issue is [this](https://github.com/darrenhaken/dropwizard-guicier-issue9/blob/7fca9c739ea3074a13f818c4a740e9e3c8d98dd8/build.gradle#L21) line. `dropwizard-guicier` 1.0.0.1 relies on dropwizard 1.0.0-rc3. I changed that variable to 1.0.0-rc3 and the app started up without exception. I'd recommend using something like the [maven-dependency-versions-check-plugin](https://github.com/ning/maven-dependency-versions-check-plugin) (not sure if there's a gradle analog) to make sure that the resolved versions of dependencies satisfy all of the transitive requirements. For example if I try to build with the dropwizard version set to 0.9.3 I get a slew of validation errors from Maven:

```
[ERROR] Found a problem with the direct dependency io.dropwizard:dropwizard-servlets of the current project
  Expected version is 0.9.3
  Resolved version is 0.9.3
  Version 0.9.3 was expected by artifact: io.dropwizard:dropwizard-core
  Version 1.0.0-rc3 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the direct dependency io.dropwizard:dropwizard-lifecycle of the current project
  Expected version is 0.9.3
  Resolved version is 0.9.3
  Version 0.9.3 was expected by artifact: io.dropwizard:dropwizard-core
  Version 1.0.0-rc3 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the direct dependency io.dropwizard:dropwizard-core of the current project
  Expected version is 0.9.3
  Resolved version is 0.9.3
  Version 1.0.0-rc3 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the direct dependency com.fasterxml.jackson.core:jackson-annotations of the current project
  Expected version is 2.6.7
  Resolved version is 2.6.7
  Version 2.6.0 was expected by artifacts: io.dropwizard:dropwizard-core, io.dropwizard:dropwizard-lifecycle, io.dropwizard:dropwizard-servlets
  Version 2.7.4 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency com.fasterxml.jackson.core:jackson-core
  Resolved version is 2.6.7
  Version 2.6.7 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.7.4 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency com.fasterxml.jackson.core:jackson-databind
  Resolved version is 2.6.7
  Version 2.6.7 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.7.4 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency com.fasterxml.jackson.dataformat:jackson-dataformat-yaml
  Resolved version is 2.6.7
  Version 2.6.7 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.7.4 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency com.fasterxml.jackson.datatype:jackson-datatype-guava
  Resolved version is 2.6.7
  Version 2.6.7 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.7.4 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency com.fasterxml.jackson.datatype:jackson-datatype-jdk7
  Resolved version is 2.6.7
  Version 2.6.7 was expected by artifact: io.dropwizard:dropwizard-core
[ERROR] Found a problem with the dependency com.fasterxml.jackson.datatype:jackson-datatype-joda
  Resolved version is 2.6.7
  Version 2.6.7 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.7.4 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency com.fasterxml.jackson.jaxrs:jackson-jaxrs-base
  Resolved version is 2.6.7
  Version 2.6.7 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.7.4 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency com.fasterxml.jackson.jaxrs:jackson-jaxrs-json-provider
  Resolved version is 2.6.7
  Version 2.6.7 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.7.4 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency com.fasterxml.jackson.module:jackson-module-afterburner
  Resolved version is 2.6.7
  Version 2.6.7 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.7.4 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency com.fasterxml.jackson.module:jackson-module-jaxb-annotations
  Resolved version is 2.6.7
  Version 2.6.7 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.7.4 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency io.dropwizard:dropwizard-configuration
  Resolved version is 0.9.3
  Version 0.9.3 was expected by artifact: io.dropwizard:dropwizard-core
  Version 1.0.0-rc3 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency io.dropwizard:dropwizard-jackson
  Resolved version is 0.9.3
  Version 0.9.3 was expected by artifact: io.dropwizard:dropwizard-core
  Version 1.0.0-rc3 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency io.dropwizard:dropwizard-jersey
  Resolved version is 0.9.3
  Version 0.9.3 was expected by artifact: io.dropwizard:dropwizard-core
  Version 1.0.0-rc3 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency io.dropwizard:dropwizard-jetty
  Resolved version is 0.9.3
  Version 0.9.3 was expected by artifact: io.dropwizard:dropwizard-core
  Version 1.0.0-rc3 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency io.dropwizard:dropwizard-logging
  Resolved version is 0.9.3
  Version 0.9.3 was expected by artifact: io.dropwizard:dropwizard-core
  Version 1.0.0-rc3 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency io.dropwizard:dropwizard-metrics
  Resolved version is 0.9.3
  Version 0.9.3 was expected by artifact: io.dropwizard:dropwizard-core
  Version 1.0.0-rc3 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency io.dropwizard:dropwizard-util
  Resolved version is 0.9.3
  Version 0.9.3 was expected by artifacts: io.dropwizard:dropwizard-core, io.dropwizard:dropwizard-lifecycle, io.dropwizard:dropwizard-servlets
  Version 1.0.0-rc3 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency io.dropwizard:dropwizard-validation
  Resolved version is 0.9.3
  Version 0.9.3 was expected by artifact: io.dropwizard:dropwizard-core
  Version 1.0.0-rc3 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency net.sourceforge.argparse4j:argparse4j
  Resolved version is 0.6.0
  Version 0.6.0 was expected by artifact: io.dropwizard:dropwizard-core
  Version 0.7.0 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency org.glassfish.jersey.containers:jersey-container-servlet
  Resolved version is 2.22.1
  Version 2.22.1 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.23 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency org.glassfish.jersey.ext:jersey-bean-validation
  Resolved version is 2.22.1
  Version 2.22.1 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.23 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
[ERROR] Found a problem with the dependency org.glassfish.jersey.ext:jersey-metainf-services
  Resolved version is 2.22.1
  Version 2.22.1 was expected by artifact: io.dropwizard:dropwizard-core
  Version 2.23 was expected by artifact: com.hubspot.dropwizard:dropwizard-guicier
```

**Comment by darrenhaken** [comment]
Ah! So this is an issue with requiring Dropwizard 1.x?!

**Comment by jhaber** [comment]
It appears so, I'm amazed the app actually started up with all the 0.9.3 deps

**Comment by darrenhaken** [comment]
OK I'll hold off using guicier until they release 1.0 then.

I'm hoping it is any day now considering they're on their final RC

**Comment by darrenhaken** [comment]
Thanks for checking out the issue by the way

**Comment by jhaber** [comment]
No problem! I'll cut a new release of dropwizard-guicier once dropwizard 1.0 comes out of RC

**Comment by jhaber** [comment]
Hey @darrenhaken just wanted to follow up now that dropwizard 1.0.0 has been released. I just pushed dropwizard-guicier 1.0.0.2 to maven central which uses dropwizard 1.0.0

**Comment by darrenhaken** [comment]
@jhaber Thanks for letting me know that's great. I'll upgrade the packages tomorrow 👍
